owner: zuko-xdev # GitHub username
repo: status # GitHub repository name #user-agent: tansautn
sites: # List of endpoints to track
    -   name: Zuko
        url: https://ps1787.zuko.pro
        headers:
            - "X-Uptime-Bot: 1"
    -   name: POST to Zuko
        url: https://ps1787.zuko.pro
        method: POST
            headers:
                - "X-Uptime-Bot: 1"
                
status-website:
    baseUrl: /status # where "repo" is your repository name
    name: Zuko Status
