owner: "ultra-bugs"
repo: status
user-agent: tansautn
sites:
    -   name: Zuko HTTP GET
        url: https://zuko.pro
        headers:
            - "X-Uptime-Bot: 1"
    -   name: Zuko HTTP POST
        url: https://zuko.pro
        method: POST
        headers:
            - "X-Uptime-Bot: 1"
status-website:
    baseUrl: /status
    name: "Zuko Status"
