owner: zuko-xdev
repo: status
user-agent: tansautn
sites:
    -   name: Zuko
        url: https://ps1787.zuko.pro
        headers:
            - "X-Uptime-Bot: 1"
    -   name: POST to Zuko
        url: https://ps1787.zuko.pro
        method: POST
        headers:
            - "X-Uptime-Bot: 1"
                
status-website:
    baseUrl: /status
    name: "Zuko Status"
