owner: zuko-xdev # GitHub username
repo: status # GitHub repository name
user-agent: tansautn
sites: # List of endpoints to track
  - name: Zuko
    url: https://ps1787.zuko.pro
  - name: Zuko (POST)
    url: https://ps1787.zuko.pro
    method: POST
assignees: # Users to assign downtime issues (optional)
