owner: "ultra-bugs"
repo: status
user-agent: tansautn
sites:
    -   name: Zuko's Main Server [GET]
        url: https://zuko.pro
        headers:
            - "X-Uptime-Bot: 1"
    -   name: Zuko's Main Server [POST]
        url: https://zuko.pro
        method: POST
        headers:
            - "X-Uptime-Bot: 1"
    -   name: "Lalita landing webpage"
        url: https://lalitadesignqni.com
        method: GET
        headers:
            - "X-Uptime-Bot: 1"
status-website:
    baseUrl: /status
    name: "Zuko Status"
